### ISSUE TITLE
broken heroku link

### ISSUE THREAD

**Issue by cjavdev** [discotroll65/vensei#1]

**Comment by discotroll65** [comment]
Yeah haven't set that up yet...should I just get the domain first and then hook it up through heroku? In other words, should I prioritize getting the custom "www.vensei.com" domain up and running tomorrow, or is just using a "vensei.herokuapp.com" good enough for now?

**Comment by cjavdev** [comment]
the herokuapp one is good for now. just leaving this issue open as a reminder to update the readme

**Comment by discotroll65** [comment]
Deployed to heroku, got basic layout down
